import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {units} from '../public/roster.js';
import {makeEngine} from '../worker/wasm.js';
const run=makeEngine(new WebAssembly.Module(readFileSync(new URL('../worker/engine.wasm',import.meta.url))));
test('Rust rejects foreign pieces and unknown commands without changing the treasury',()=>{const state=run({op:'new',seed:915,difficulty:2}).state;const id=state.squads.find(u=>u.owner===1).id;for(const kind of ['move','ability','explore']){const r=run({op:'command',state,player:0,kind,from:id,to:0});assert.equal(r.error,3);assert.equal(r.state.players[0].gold,170);}assert.equal(run({op:'command',state,kind:'march'}).error,6);});
test('server entropy changes discoveries without changing the public world',()=>{const a=run({op:'new',seed:42,hidden_rolls:Array(642).fill(12)}).state,b=run({op:'new',seed:42,hidden_rolls:Array(642).fill(7)}).state;assert.deepEqual(a.tiles,b.tiles);assert.ok(a.discoveries.length>0);assert.equal(b.discoveries.length,0);const view=run({op:'view',state:a,player:0}).state;assert.ok(view.discoveries.length<a.discoveries.length);assert.equal(view.hidden_rolls,undefined);assert.equal(view.players[1].unlocked,undefined);});
test('eight-player WASM play preserves occupancy and only permits conquest or orbital spaceflight',()=>{let state=run({op:'new',seed:93001,difficulty:2}).state;state.players.forEach(p=>p.bot=true);state=run({op:'step',state,ticks:2200}).state;if(state.winner>=0){const p=state.players[state.winner];assert.ok(state.players.filter(p=>p.alive).length===1||(p.launch>=180&&p.unlocked.includes(10)));}assert.ok(state.cities.length>=8);assert.equal(new Set(state.squads.filter(u=>u.boarded_on==null).map(u=>u.tile)).size,state.squads.filter(u=>u.boarded_on==null).length);assert.ok(state.players.every(p=>p.gold>=0));});

test('passive WASM civilizations cannot win from old influence or capital counters',()=>{let state=run({op:'new',seed:42,players:2}).state;state.players.forEach(p=>{p.bot=false;p.mandate=65535;p.domination=65535;});state=run({op:'step',state,ticks:2200}).state;assert.equal(state.winner,-1);assert.ok(state.players.every(p=>p.mandate===0&&p.domination===0));});
