import {readFileSync,writeFileSync} from 'node:fs';
const roster=JSON.parse(readFileSync(new URL('../data/units.json',import.meta.url),'utf8'));
if(roster.units.length!==36||roster.units.filter(u=>u.researchable).length!==33)throw Error('Expected 33 technologies and 3 starting units');
for(const [id,u] of roster.units.entries())if(u.id!==id||u.prerequisites.includes(id))throw Error('Invalid unit identity/prerequisite');
writeFileSync(new URL('../public/roster.js',import.meta.url),'// Generated by scripts/roster.mjs from data/units.json.\nexport const roster='+JSON.stringify(roster)+';\nexport const units=roster.units;\nexport const naval=k=>units[k]?.domain===\'sea\';\nexport const air=k=>units[k]?.domain===\'air\';\n');
