import {readFileSync,writeFileSync} from 'node:fs';
const roster=JSON.parse(readFileSync(new URL('../data/units.json',import.meta.url),'utf8'));
if(roster.units.length!==36||roster.units.filter(u=>u.researchable).length!==33)throw Error('Expected 33 technologies and 3 starting units');
for(const [id,u] of roster.units.entries())if(u.id!==id||u.prerequisites.includes(id))throw Error('Invalid unit identity/prerequisite');
// Validate the authored DAG and era layout before either client or engine builds.
const visited=new Set(),visiting=new Set(),positions=new Set();
function visit(id){
 if(visiting.has(id))throw Error('Technology prerequisites contain a cycle');
 if(visited.has(id))return;
 const u=roster.units[id];
 if(!u?.researchable)throw Error('Prerequisite must be a technology');
 visiting.add(id);
 for(const parent of u.prerequisites){
  const p=roster.units[parent];
  if(!p||p.era>u.era||p.tree[0]>=u.tree[0])throw Error('Prerequisite must precede technology on the timeline');
  visit(parent);
 }
 visiting.delete(id);visited.add(id);
}
for(const u of roster.units.filter(u=>u.researchable)){
 if(!Array.isArray(u.tree)||u.tree.length!==2||u.tree.some(n=>!Number.isInteger(n)||n<0)||Math.floor(u.tree[0]/3)!==u.era)throw Error('Invalid era position');
 const position=u.tree.join(',');if(positions.has(position))throw Error('Overlapping technologies');positions.add(position);
 visit(u.id);
}
writeFileSync(new URL('../public/roster.js',import.meta.url),'// Generated by scripts/roster.mjs from data/units.json.\nexport const roster='+JSON.stringify(roster)+';\nexport const units=roster.units;\nexport const naval=k=>units[k]?.domain===\'sea\';\nexport const air=k=>units[k]?.domain===\'air\';\n');
